font = { normal = { family = "JetBrainsMono Nerd Font" }, size = 13, offset = { x = 0, y = 12 }, glyph_offset = { x = 0, y = 6 }}

window = { blur = false, decorations = "Buttonless", opacity = 1, padding = { x = 0, y = 0 } }

[env]
term = "xterm-256color"

