general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark_hard.toml"]
# general.import = ["~/.config/alacritty/themes/themes/horizon_dark.toml"]

font = { normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }, bold = { family = "JetBrainsMono Nerd Font", style = "Semibold" }, size = 12.5, offset = { x = 1, y = 10 }, glyph_offset = { x = 0, y = 6 }}

# window = { decorations = "Buttonless", blur = false, opacity = 1, dynamic_padding = true, startup_mode = "Maximized" }
window = { padding = { x = 0, y = 0 }, blur = false, opacity = 1, startup_mode = "Maximized", decorations = "Buttonless" }


[env]
term = "xterm-256color"

