import = ["~/.config/alacritty/themes/gruvbox-hard-dark.toml"]

font = { normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }, bold = { family = "JetBrainsMono Nerd Font", style = "Semibold" }, size = 13, offset = { x = 0, y = 12 }, glyph_offset = { x = 0, y = 6 }}

window = { decorations = "Buttonless", blur = false, opacity = 1, dynamic_padding = true, startup_mode = "Maximized" }

[env]
term = "xterm-256color"

