import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

#font = { normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }, size = 15 }
font = { normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }, size = 13, offset = { x = 0, y = 12 }, glyph_offset = { x = 0, y = 6 }}

window = { opacity = 1 }

