import = ["~/.config/alacritty/themes/rose-pine.toml"]

font = { normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }, bold = { family = "JetBrainsMono Nerd Font", style = "Semibold" }, size = 12.5, offset = { x = 0, y = 12 }, glyph_offset = { x = 0, y = 6 }}

window = { decorations = "Buttonless", blur = false, opacity = 1, padding = { x = 0, y = 0 }, startup_mode = "Maximized" }

[env]
term = "xterm-256color"

