# theme = "horizon-dark"
# theme = "rose_pine_moon"
theme = "gruvbox_dark_hard"

[keys.normal]
a = ["move_char_right", "insert_mode"]
b = { d = ":buffer-close" }
"left" = ":buffer-previous"
"right" = ":buffer-next"
"S-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"S-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"S-h" = ["goto_line_start"]
"S-l" = ["goto_line_end"]

[keys.insert]
j = { k = "normal_mode" }

[editor]
bufferline = "always"
cursorline = true

[editor.cursor-shape]
insert = "bar"

