theme = "wasson"

[keys.normal]
"C-k" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"C-j" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]

[keys.select]
"C-k" = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
"C-j" = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]
