[[language]]
name = "ruby"
formatter = { command = "bundle", args = [ "exec", "stree", "format" ]}
language-servers = [{ name = "ruby-lsp", except-features = ["diagnostics"] }, { name = "rubocop", only-features = ["diagnostics"] }]
auto-format = true
auto-pairs = { "(" = ")", "[" = "]", "{" = "}", "|" = "|" }

[language-server.ruby-lsp]
command = "ruby-lsp"

[language-server.rubocop]
command = "bundle"
# args = ["exec", "rubocop"]
args = ["exec", "rubocop", "--lsp"]

[[language]]
name = "erb"
file-types = ["erb", "html"]
language-servers = [ "tailwindcss-ls" ]

[language.auto-pairs]
'<' = '>'
'%' = '%'
"'" = "'"
'"' = '"'

[[language]]
name = "javascript"
formatter = { command = "/Users/austin/.asdf/installs/nodejs/20.12.0/lib/node_modules/prettier/bin/prettier.cjs", args = ["--parser", "typescript" ] }
auto-format = false
file-types = ["js", "jsx"]

[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs", "csx", "cake"]
roots = ["sln", "csproj"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "\t" }
language-servers = [ "omnisharp" ]

[[language]]
name = "typescript"
formatter = { command = '/Users/austin/.asdf/installs/nodejs/20.12.0/lib/node_modules/prettier/bin/prettier.cjs', args = ["--parser", "typescript"] }
file-types=["ts", "tsx"]
auto-format = true

[[language]]
name = "tsx"
file-types = ["tsx"]
formatter = { command = '/Users/austin/.asdf/installs/nodejs/20.12.0/lib/node_modules/prettier/bin/prettier.cjs', args = ["--stdin-filename", "file.tsx"] }
language-servers = ["tailwindcss-ls", "emmet-ls"]
auto-format = true

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html", typescript = "html", "*.tsx" = "html" } }

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

