# -- ruby --
# -- Solargraph --
[language-server]
[language-server.ruby-lsp]
command = "ruby-lsp"
config.diagnostics=true
config.formatting=false

[[language]]
name = "ruby"
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }
auto-format = true
language-servers=[{name="ruby-lsp"}]

