# -- ruby --
# -- Solargraph --
[language-server]
[language-server.ruby-lsp]
name = "ruby-lsp"
command = "ruby-lsp"

[language-server.solargraph]
name = "solargraph"
command = "solargraph"
args = ["stdio"]
hover = true

[[language]]
name = "ruby"
auto-format = true
file-types = ["rb", "erb", "Gemfile", "Rakefile", "Procfile"]
shebangs = ["ruby"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [{ name = "solargraph" }]
