# -- ruby --
# -- Solargraph --
[language-server]
[language-server.solargraph]
config.diagnostics=true
config.formatting=false

[[language]]
name = "ruby"
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }
auto-format = true
language-servers=[{name="solargraph"}]

