[[language]]
name = "ruby"
formatter = { command = "bundle", args = [ "exec", "stree", "format" ]}
language-servers = [{ name = "ruby-lsp", except-features = ["diagnostics"] }, { name = "rubocop", only-features = ["diagnostics"] }]
auto-format = true
auto-pairs = { "(" = ")", "[" = "]", "{" = "}", "|" = "|" }

[language-server.ruby-lsp]
command = "ruby-lsp"

[language-server.rubocop]
command = "bundle"
# args = ["exec", "rubocop"]
args = ["exec", "rubocop", "--lsp"]

[[language]]
name = "erb"
file-types = ["erb", "html"]
language-servers = [ "tailwindcss-ls" ]

[language.auto-pairs]
'<' = '>'
'%' = '%'
"'" = "'"
'"' = '"'

[[language]]
name = "javascript"
auto-format = false
file-types = ["js", "jsx"]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
file-types=["ts", "tsx"]
auto-format = true

[[language]]
name = "tsx"
file-types = ["tsx"]
formatter = { command = 'prettier', args = ["--parser", "babel-ts"] }
language-servers = ["typescript-language-server", "tailwindcss-ls", "emmet-ls"]
block-comment-tokens = [{ start = "{/*", end = "*/}" }]
auto-format = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html", typescript = "html", "*.tsx" = "html" } }

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

