"ui.background" = { bg = "base" }
"ui.selection" = { bg = "glow", fg = "base" }
"ui.text" = "white"
"ui.linenr" = { fg = "#454545" }
"ui.linenr.selected" = { fg = "glow" }
"ui.statusline" = { fg = "silver" }
"ui.cursor.select" = { bg = "glow", fg = "base" }

"diagnostic.hint" = { underline = { color = "silver", style = "curl" } }
"diagnostic.info" = { underline = { color = "delta", style = "curl" } }
"diagnostic.warning" = { underline = { color = "lightning", style = "curl" } }
"diagnostic.error" = { underline = { color = "apricot", style = "curl" } }

warning = "lightning"
error = "apricot"
info = "glow"
hint = "silver"

attribute = "orange"
comment = "#676767"
constant = "yellow"
constructor = "#F6C88F"
"function.method" = "glow"
keyword = "peach"
namespace = "yellow"
operator = "yellow"
punctuation = "yellow"
string = "#629E7E"
"string.special.symbol" = "#AEC9D6"
"variable.parameter" = "lightning"
variable = "lavender"


[palette]
apricot = "#f47868"
base = "#1e1f22"
delta = "#6f44f0"
glow = "#ece5e1"
lavender = "#a4a0e8"
lightning = "#ffcd1c"
orange = "#ff7d00"
peach = "#c59172"
silver = "#cccccc"

