"ui.background" = { bg = "base" }
"ui.selection" = { bg = "glow", fg = "base" }
"ui.text" = "white"
"ui.linenr" = { fg = "#454545" }
"ui.linenr.selected" = { fg = "glow" }
"ui.statusline" = { fg = "lavender" }
"ui.cursor.select" = { bg = "glow", fg = "base" }

"diagnostic.hint" = { underline = { color = "silver", style = "curl" } }
"diagnostic.info" = { underline = { color = "delta", style = "curl" } }
"diagnostic.warning" = { underline = { color = "lightning", style = "curl" } }
"diagnostic.error" = { underline = { color = "apricot", style = "curl" } }

warning = "lightning"
error = "apricot"
info = "glow"
hint = "silver"

attribute = "lavender"
comment = "#676767"
constant = "yellow"
constructor = "#FF7D00"
function = "lavender"
keyword = "lavender"
namespace = "yellow"
operator = "yellow"
punctuation = "yellow"
string = "#E9E6FF"
"string.special.symbol" = "#62b7e1"
variable = "#F28482"


[palette]
apricot = "#f47868"
base = "#1e1f22"
delta = "#6f44f0"
glow = "#ece5e1"
lavender = "#a4a0e8"
lightning = "#ffcd1c"
silver = "#cccccc"

